from fpdf import FPDF
import datetime

class FarmIQPDF(FPDF):
    def header(self):
        # Set font for the header
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(22, 163, 74) # #16a34a FarmIQ Green
        self.cell(0, 10, 'FarmIQ Kenya', ln=True, align='C')
        self.set_font('helvetica', 'I', 10)
        self.set_text_color(100)
        self.cell(0, 10, 'Agriculture Intelligence Platform', ln=True, align='C')
        self.ln(10)
        # Line break
        self.set_draw_color(230)
        self.line(10, 32, 200, 32)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by FarmIQ Kenya MVP', align='C')

def generate_report_pdf(result, lang="English"):
    pdf = FarmIQPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Translation keys
    labels = {
        "English": {
            "title": "AGRONOMIC ADVICE REPORT",
            "date": "Date",
            "county": "County",
            "zone": "Agro-Zone",
            "crop": "Target Crop",
            "acres": "Farm Size",
            "soil_title": "1. SOIL DIAGNOSTIC PROFILE",
            "budget_title": "2. FINANCIAL BUDGET (Per Acre)",
            "advice_title": "3. ACTIONABLE ADVICE",
            "official": "OFFICIAL AGRONOMIC RECORD",
            "status": "Status"
        },
        "Kiswahili": {
            "title": "RIPOTI YA USHAURI WA KILIMO",
            "date": "Tarehe",
            "county": "Kaunti",
            "zone": "Eneo la Kilimo",
            "crop": "Zao la Shamba",
            "acres": "Ukubwa wa Shamba",
            "soil_title": "1. HALI YA UDONGO WAKO",
            "budget_title": "2. MAKADIRIO YA GHARAMA",
            "advice_title": "3. USHAURI WA KUCHUKUA HATUA",
            "official": "KUMBUKUMBU RASMI YA KILIMO",
            "status": "Hali"
        }
    }
    t = labels[lang]
    
    # Title Section
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_text_color(0)
    pdf.cell(0, 10, t["title"], ln=True, align='L')
    
    # Meta Data
    pdf.set_font('helvetica', '', 10)
    pdf.cell(40, 7, f"{t['date']}:", 0)
    pdf.cell(0, 7, datetime.datetime.now().strftime("%Y-%m-%d"), 1, ln=True)
    pdf.cell(40, 7, f"{t['county']}:", 0)
    pdf.cell(0, 7, result["county_data"]["County"], 0, ln=True)
    pdf.cell(40, 7, f"{t['crop']}:", 0)
    pdf.cell(0, 7, result["crop"], 0, ln=True)
    pdf.cell(40, 7, f"{t['acres']}:", 0)
    pdf.cell(0, 7, f"{result['budget']['farm_size']} Acres", 0, ln=True)
    pdf.ln(10)

    # 1. Soil Diagnostic Section
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, t["soil_title"], ln=True, fill=True)
    pdf.ln(2)
    pdf.set_font('helvetica', '', 10)
    
    def add_soil_row(name, val, unit, is_bad):
        pdf.cell(60, 7, name, 0)
        pdf.set_font('helvetica', 'B', 10)
        status_text = "!" if is_bad else "OK"
        pdf.cell(30, 7, f"{val} {unit}", 0)
        if is_bad:
            pdf.set_text_color(200, 0, 0)
            pdf.cell(0, 7, "Deficit / Acidic", 0, ln=True)
        else:
            pdf.set_text_color(0, 150, 0)
            pdf.cell(0, 7, "Normal / Healthy", 0, ln=True)
        pdf.set_text_color(0)
        pdf.set_font('helvetica', '', 10)

    add_soil_row("Soil pH Level:", result["county_data"].get("pH", "N/A"), "", result.get("is_acidic", False))
    add_soil_row("Extractable Nitrogen (N):", result["county_data"].get("Total Nitrogen (mg/kg)", "N/A"), "mg/kg", result.get("is_n_low", False))
    add_soil_row("Extractable Phosphorus (P):", result["county_data"].get("Extractable Phosphorus (mg/kg)", "N/A"), "mg/kg", result.get("is_p_low", False))
    add_soil_row("Extractable Potassium (K):", result["county_data"].get("Extractable Potassium (mg/kg)", "N/A"), "mg/kg", result.get("is_k_low", False))
    pdf.ln(10)

    # 2. Budget Section
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, t["budget_title"], ln=True, fill=True)
    pdf.ln(2)
    pdf.set_font('helvetica', '', 10)
    for line in result["budget"]["breakdown"]:
        pdf.cell(0, 7, f"- {line}", ln=True)
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 10, f"Total Estimated Budget: KES {result['budget']['total_budget']:,}", ln=True)
    pdf.ln(10)

    # 3. Actionable Advice
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, t["advice_title"], ln=True, fill=True)
    pdf.ln(2)
    pdf.set_font('helvetica', '', 10)
    for item in result["advice"]:
        # Strip Markdown bolding and common Emojis that crash the default Helvetica font
        clean_item = item.replace("**", "")
        # Robust emoji removal using encoding fallback
        clean_item = clean_item.encode('ascii', 'ignore').decode('ascii')
        
        # Handle multi-line wrapping
        pdf.multi_cell(0, 6, f"- {clean_item.strip()}")
        pdf.ln(2)

    # Validation Stamp
    pdf.set_y(-60)
    pdf.set_draw_color(150)
    pdf.set_font('helvetica', 'B', 9)
    pdf.cell(60, 20, t["official"], 1, 0, 'C')
    
    return bytes(pdf.output())
